//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueAir.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("BlueAir.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string PickAFolder {
            get {
                return ResourceManager.GetString("PickAFolder", resourceCulture);
            }
        }
        
        public static string OpenAFileTitle {
            get {
                return ResourceManager.GetString("OpenAFileTitle", resourceCulture);
            }
        }
        
        public static string CommandNoMobileInfo {
            get {
                return ResourceManager.GetString("CommandNoMobileInfo", resourceCulture);
            }
        }
        
        public static string ShowHideOutput {
            get {
                return ResourceManager.GetString("ShowHideOutput", resourceCulture);
            }
        }
        
        public static string Downloader {
            get {
                return ResourceManager.GetString("Downloader", resourceCulture);
            }
        }
        
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        public static string TargetFolder {
            get {
                return ResourceManager.GetString("TargetFolder", resourceCulture);
            }
        }
        
        public static string DownloadAgent {
            get {
                return ResourceManager.GetString("DownloadAgent", resourceCulture);
            }
        }
        
        public static string RunCommands {
            get {
                return ResourceManager.GetString("RunCommands", resourceCulture);
            }
        }
        
        public static string BeforeCommand {
            get {
                return ResourceManager.GetString("BeforeCommand", resourceCulture);
            }
        }
        
        public static string AfterCommand {
            get {
                return ResourceManager.GetString("AfterCommand", resourceCulture);
            }
        }
        
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        public static string AllowFailure {
            get {
                return ResourceManager.GetString("AllowFailure", resourceCulture);
            }
        }
        
        public static string NewFolder {
            get {
                return ResourceManager.GetString("NewFolder", resourceCulture);
            }
        }
        
        public static string NewFile {
            get {
                return ResourceManager.GetString("NewFile", resourceCulture);
            }
        }
        
        public static string RemoveSelectedDO {
            get {
                return ResourceManager.GetString("RemoveSelectedDO", resourceCulture);
            }
        }
        
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        public static string URL {
            get {
                return ResourceManager.GetString("URL", resourceCulture);
            }
        }
        
        public static string MainFolder {
            get {
                return ResourceManager.GetString("MainFolder", resourceCulture);
            }
        }
        
        public static string AutoRemoveFinished {
            get {
                return ResourceManager.GetString("AutoRemoveFinished", resourceCulture);
            }
        }
        
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        public static string ThemeSetting {
            get {
                return ResourceManager.GetString("ThemeSetting", resourceCulture);
            }
        }
        
        public static string UseSystemTheme {
            get {
                return ResourceManager.GetString("UseSystemTheme", resourceCulture);
            }
        }
        
        public static string UseTheme {
            get {
                return ResourceManager.GetString("UseTheme", resourceCulture);
            }
        }
        
        public static string ThemeLight {
            get {
                return ResourceManager.GetString("ThemeLight", resourceCulture);
            }
        }
        
        public static string ThemeDark {
            get {
                return ResourceManager.GetString("ThemeDark", resourceCulture);
            }
        }
        
        public static string ColorSetting {
            get {
                return ResourceManager.GetString("ColorSetting", resourceCulture);
            }
        }
        
        public static string UseDefaultColor {
            get {
                return ResourceManager.GetString("UseDefaultColor", resourceCulture);
            }
        }
        
        public static string UseColor {
            get {
                return ResourceManager.GetString("UseColor", resourceCulture);
            }
        }
        
        public static string AgentListTitle {
            get {
                return ResourceManager.GetString("AgentListTitle", resourceCulture);
            }
        }
        
        public static string AgentRemoveSelected {
            get {
                return ResourceManager.GetString("AgentRemoveSelected", resourceCulture);
            }
        }
        
        public static string AgentInstallNew {
            get {
                return ResourceManager.GetString("AgentInstallNew", resourceCulture);
            }
        }
        
        public static string AgentCommandInfo {
            get {
                return ResourceManager.GetString("AgentCommandInfo", resourceCulture);
            }
        }
        
        public static string VariablesTitle {
            get {
                return ResourceManager.GetString("VariablesTitle", resourceCulture);
            }
        }
        
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        public static string AboutDescription {
            get {
                return ResourceManager.GetString("AboutDescription", resourceCulture);
            }
        }
        
        public static string AboutLicense {
            get {
                return ResourceManager.GetString("AboutLicense", resourceCulture);
            }
        }
        
        public static string AboutTechnologies {
            get {
                return ResourceManager.GetString("AboutTechnologies", resourceCulture);
            }
        }
        
        public static string SaveAFile {
            get {
                return ResourceManager.GetString("SaveAFile", resourceCulture);
            }
        }
        
        public static string PickATargetFolder {
            get {
                return ResourceManager.GetString("PickATargetFolder", resourceCulture);
            }
        }
        
        public static string PickAnAgentfile {
            get {
                return ResourceManager.GetString("PickAnAgentfile", resourceCulture);
            }
        }
        
        public static string AgentFileDesc {
            get {
                return ResourceManager.GetString("AgentFileDesc", resourceCulture);
            }
        }
    }
}
