//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueAir.CLI.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translations {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("BlueAir.CLI.Resources.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string CancelRequested {
            get {
                return ResourceManager.GetString("CancelRequested", resourceCulture);
            }
        }
        
        internal static string DownloadTook {
            get {
                return ResourceManager.GetString("DownloadTook", resourceCulture);
            }
        }
        
        internal static string ReadingInputFile {
            get {
                return ResourceManager.GetString("ReadingInputFile", resourceCulture);
            }
        }
        
        internal static string StartAutoSaveFile {
            get {
                return ResourceManager.GetString("StartAutoSaveFile", resourceCulture);
            }
        }
        
        internal static string StartInputFile {
            get {
                return ResourceManager.GetString("StartInputFile", resourceCulture);
            }
        }
        
        internal static string StartOutputFile {
            get {
                return ResourceManager.GetString("StartOutputFile", resourceCulture);
            }
        }
        
        internal static string StartProgress {
            get {
                return ResourceManager.GetString("StartProgress", resourceCulture);
            }
        }
        
        internal static string TooFewArguments {
            get {
                return ResourceManager.GetString("TooFewArguments", resourceCulture);
            }
        }
        
        internal static string UsageAutoSave {
            get {
                return ResourceManager.GetString("UsageAutoSave", resourceCulture);
            }
        }
        
        internal static string UsageHelp {
            get {
                return ResourceManager.GetString("UsageHelp", resourceCulture);
            }
        }
        
        internal static string UsageInputXML {
            get {
                return ResourceManager.GetString("UsageInputXML", resourceCulture);
            }
        }
        
        internal static string UsageOptionsTitle {
            get {
                return ResourceManager.GetString("UsageOptionsTitle", resourceCulture);
            }
        }
        
        internal static string UsageText {
            get {
                return ResourceManager.GetString("UsageText", resourceCulture);
            }
        }
        
        internal static string UsageTimer {
            get {
                return ResourceManager.GetString("UsageTimer", resourceCulture);
            }
        }
        
        internal static string VersionInfo {
            get {
                return ResourceManager.GetString("VersionInfo", resourceCulture);
            }
        }
        
        internal static string UsageVerbose {
            get {
                return ResourceManager.GetString("UsageVerbose", resourceCulture);
            }
        }
        
        internal static string UsageVersion {
            get {
                return ResourceManager.GetString("UsageVersion", resourceCulture);
            }
        }
        
        internal static string UsageXTimer {
            get {
                return ResourceManager.GetString("UsageXTimer", resourceCulture);
            }
        }
    }
}
